---
- name: "Common setup for all hosts"
  hosts: all
  become: true
  gather_facts: true
  
  tasks:
    - name: "Display host information"
      debug:
        msg: "Host: {{ inventory_hostname }}"

    - name: "Install common packages"
      package:
        name: "{{ common_packages }}"
        state: present
      when: common_packages is defined

- name: "Configure web servers"
  hosts: webservers
  become: true
  
  tasks:
    - name: "Web server configuration"
      debug:
        msg: "Configuring web server: {{ inventory_hostname }}"
